[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
board_build.embed_files =
  assets/faces/happy.jpg
  assets/faces/startled.jpg
  assets/faces/curious.jpg
  assets/faces/excited.jpg
  assets/faces/surprised.jpg
  assets/faces/sleepy.jpg
  assets/faces/sad.jpg
  assets/faces/wink.jpg
  assets/faces/thinking.jpg
  assets/faces/talk_small.jpg
  assets/faces/talk_closed.jpg
  assets/faces/talk_medium.jpg
  assets/faces/talk_wide.jpg
lib_deps =
  m5stack/M5Unified @ ^0.2.11
  knolleary/PubSubClient @ ^2.8
  tzapu/WiFiManager @ ^2.0.17
  links2004/WebSockets @ ^2.6.1
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
monitor_filters = esp32_exception_decoder
